file(GLOB_RECURSE starml_all_srcs "starml/*.*")
foreach(starml_single_file ${starml_all_srcs})
  if("${starml_single_file}" MATCHES "^${PROJECT_SOURCE_DIR}/starml/.*\\.cpp$")
    list(APPEND of_all_obj_cc ${starml_single_file})
  endif()
  if("${starml_single_file}" MATCHES "^${PROJECT_SOURCE_DIR}/starml/.*\\.cu$")
    if (USE_CUDA)
      list(APPEND of_all_obj_cc ${starml_single_file})
    endif()
  endif()
  if("${starml_single_file}" MATCHES "^${PROJECT_SOURCE_DIR}/starml/.*\\.cuh$")
    if (USE_CUDA)
      list(APPEND of_all_obj_cc ${starml_single_file})
    endif()
  endif()
  if("${starml_single_file}" MATCHES "^${PROJECT_SOURCE_DIR}/starml/.*\\.h$")
    list(APPEND of_all_obj_cc ${starml_single_file})
  endif()
endforeach()

add_library(starml_internal SHARED ${of_all_obj_cc})
target_include_directories(starml_internal PUBLIC ${PROJECT_SOURCE_DIR})
target_link_libraries(starml_internal ${starml_third_party_libs})